#application.yml


---
#로컬 환경.
server:
  port: 8080
  tomcat:
    use-relative-redirects: true

#spring.profiles.include: console-logging

logging:
  level:
    '[org.springframework.web.reactive.function.client.ExchangeFunctions]': DEBUG
    '[org.hibernate.SQL]': debug
    '[org.hibernate.type]' : trace

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      pool-name: HikariPool-market-doctor
      maximum-pool-size: 16
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.diveand.com:33306/keyword_monitor?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: keyword_monitor
    password: Zldnjemahslxj123!@#
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
  jpa:
    open-in-view: false
    #show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: validate
      jdbc:
        order_inserts: true
        order_updates: true
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        default_batch_fetch_size: 1000

  devtools:
    livereload:
      enabled: true

#spring docs 설정
springdoc:
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
  cache:
    disabled: false
  override-with-generic-response: false

firebase:
  account-key: /home/ec2-user/keyword-api/firebase_service_account_key.json
  service-id: firebase-adminsdk-qwwdw@marketdoctor-f5a69.iam.gserviceaccount.com

#3rd-party url
api-info:
  naver:
    news: https://openapi.naver.com/v1/search/news.json
    blog: https://openapi.naver.com/v1/search/blog.json
  kakao:
    oauth-token : https://kauth.kakao.com/oauth/token
    redirect-url : https://desk.marketdoctor.ai/auth/oauth/callback
    user-profile : https://kapi.kakao.com/v2/user/me
