#application.yml


---
#운영 환경.
server:
  port: 8080
  tomcat:
    use-relative-redirects: true

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

  config:
    activate:
      on-profile: prod

  devtools:
    livereload:
      enabled: true

#spring docs 설정
springdoc:
  swagger-ui:
    path: swagger-ui.html
  api-docs:
    enabled: false
    path: /api-docs
  cache:
    disabled: true
  override-with-generic-response: false

firebase:
  account-key: firebase_service_account_key.json
  service-id: firebase-adminsdk-qwwdw@marketdoctor-f5a69.iam.gserviceaccount.com
#3rd-party url
api-info:
  naver:
    news: https://openapi.naver.com/v1/search/news.json
    blog: https://openapi.naver.com/v1/search/blog.json
  kakao:
    oauth-token : https://kauth.kakao.com/oauth/token
    redirect-url : https://desk.marketdoctor.ai/auth/oauth/callback
    user-profile : https://kapi.kakao.com/v2/user/me